goodluck_english_school/src/english_school/news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('all', views.NewsList.as_view(), name='news_list'),
    path('<news_id>/detail', views.NewsDetail.as_view(), name='news_detail'),
]

goodluck_english_school/src/english_school/services/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    path('all', views.ServicesList.as_view(), name='services_list'),
    path('<service_id>/detail', views.ServiceDetail.as_view(), name='service_detail'),
]

goodluck_english_school/src/english_school/templates/includes/cards/nested/news_card.html
{% load static %}

<a href="{% url 'news:news_detail' 1 %}" class="text-decoration-none">
  <div class="card inner py-3 px-2 bg-info bg-opacity-25 d-flex flex-row align-items-center" style="min-height:135px">
    {% if news.image %}
      <div>
        <img src="{{ news.image.url }}" alt="" class="rounded-3">
      </div>
    {% endif %}
    <div class="card-body p-0 ps-3">
      <p class="card-text text-decoration-none">
        {{news.title|truncatechars:80}}
      </p>
    </div>
  </div>
</a>

goodluck_english_school/src/english_school/templates/includes/cards/nested/service_card.html
{% load static %}

{% if service.id %}
<a href="{% url 'services:service_detail' service.id %}">
{% endif %}
  <div class="card inner">
    <img src="{{ service.image.url }}" alt="">
    <div class="card-body m-2 px-2 py-0 position-absolute top-0 end-0 rounded-pill" style="background-image:url({{ service.rate.theme_image.url }})">
      <p class="card-text text-rate shadow-sm">{{ service.rate.title }}</p>
    </div>
    <div class="card-body w-100 py-2 bg-opacity position-absolute bottom-0 start-50 translate-middle-x">
      <p class="card-text card-title text-service-title text-white">{{ service.title }}</p>
    </div>
  </div>
</a>