goodluck_english_school/src/english_school/news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('all', views.NewsList.as_view(), name='news_list'),
    path('<news_id>/detail', views.NewsDetail.as_view(), name='news_detail'),
]

goodluck_english_school/src/english_school/profiles/urls.py
from django.urls import path

from . import views

app_name = 'profiles'


urlpatterns = [
    path('<slug:username>/profile/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('<slug:username>/edit/', views.UserUpdateView.as_view(), name='user_edit'),
    path('<slug:username>/profile/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
]

goodluck_english_school/src/english_school/services/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    path('all', views.ServicesList.as_view(), name='services_list'),
    path('<service_id>/detail', views.ServiceDetail.as_view(), name='service_detail'),
]

goodluck_english_school/src/english_school/core/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from profiles.validators import is_teenager, real_age
from core.validators import starts_with_uppercase
from core.constants import (
    SMALL_FIELD_LENGTH,
    SMALL_DESCRIPTION_FIELD_LENGTH,
    GENDER_CODE_LENGTH,
    MAX_TELEGRAM_USERNAME_LENGTH,
    PRIMARY_KEY_CODE_LENGHT,
)

User = get_user_model()


class UserProfileBase(models.Model):
    class Gender(models.TextChoices):
        MALE = 'M', 'Мужской'
        FEMALE = 'F', 'Женский'
        __empty__ = 'Выберите Ваш пол:'

    gender_code = models.CharField(
        verbose_name='Пол',
        max_length=GENDER_CODE_LENGTH,
        null=True,
        blank=True,
        choices=Gender.choices,
    )
    bio = models.TextField(
        verbose_name='О себе',
        blank=True,
        null=True,
        help_text='Напишите что-нибудь о себе',
    )
    birthday_date = models.DateField(
        verbose_name='Дата рождения',
        help_text='Укажите дату Вашего рождения',
        validators=[real_age, is_teenager],
    )
    image = models.ImageField(
        verbose_name='Фотография',
        upload_to='profiles/images/',
        width_field='image_width',
        height_field='image_height',
        blank=True,
        null=True,
    )
    image_width = models.PositiveSmallIntegerField(
        verbose_name='Ширина изображения профиля',
        null=True,
        editable=False,
    )
    image_height = models.PositiveSmallIntegerField(
        verbose_name='Длина изображения профиля',
        null=True,
        editable=False,
    )
    telegram_username = models.CharField(
        verbose_name='Никнейм в Telegram',
        max_length=MAX_TELEGRAM_USERNAME_LENGTH,
        null=True,
        blank=True,
        unique=True,
        help_text='Укажите ваш никнейм в мессенджере Telegram без символа "@"',
    )

    class Meta:
        abstract = True
        ordering = ('-birthday_date',)

    def get_absolute_url(self):
        return reverse(
            'profiles:profile_detail',
            kwargs={'username': self.user.username},
        )


class SlugBasedModel(models.Model):
    code = models.SlugField(
        verbose_name='Идентификатор',
        max_length=PRIMARY_KEY_CODE_LENGHT,
        primary_key=True,
        help_text='Уникальный идентификатор из латинских символов',
    )

    class Meta:
        abstract = True


class GenericLabelBase(SlugBasedModel):

    title = models.CharField(
        verbose_name='Название',
        max_length=SMALL_FIELD_LENGTH,
        unique=True,
        validators=[starts_with_uppercase],
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True,
        null=True,
        unique=True,
        max_length=SMALL_DESCRIPTION_FIELD_LENGTH,
        validators=[starts_with_uppercase],
    )

    class Meta:
        abstract = True
        ordering = ('title',)
        indexes = [
            models.Index(
                fields=('title',),
                name='%(class)s_title_idx',
                ),
        ]

    def __str__(self):
        return self.title

goodluck_english_school/src/english_school/profiles/models.py
from django.db import models

from rates.models import Rate
from core.models import User, UserProfileBase
from core.constants import EDUCATION_CODE_LENGTH
from .mixins import ProfileRateAssignmentMixin


class TeacherRateAssignment(ProfileRateAssignmentMixin):
    teacher_profile = models.ForeignKey(
        to='TeacherProfile',
        on_delete=models.CASCADE,
        verbose_name='Профиль преподавателя',
    )

    class Meta(ProfileRateAssignmentMixin.Meta):
        db_table = 'teacher_rate_assignment'
        unique_together = ('rate', 'teacher_profile')
        indexes = [
            models.Index(
                fields=['rate'],
                name='teacher_rate_assignment_idx',
            ),
            models.Index(
                fields=['teacher_profile'],
                name='teacher_p_rate_assignment_idx',
            ),
        ]

    def __str__(self):
        return f'{self.rate} для {self.teacher_profile}'


class StudentRateAssignment(ProfileRateAssignmentMixin):
    student_profile = models.ForeignKey(
        to='StudentProfile',
        on_delete=models.CASCADE,
        verbose_name='Профиль преподавателя',
    )

    class Meta(ProfileRateAssignmentMixin.Meta):
        db_table = 'student_rate_assignment'
        unique_together = ('rate', 'student_profile')
        indexes = [
            models.Index(
                fields=['rate'],
                name='student_rate_assignment_idx',
            ),
            models.Index(
                fields=['student_profile'],
                name='student_p_rate_assignment_idx',
            ),
        ]

    def __str__(self):
        return f'{self.rate} для {self.student_profile}'


class TeacherProfile(UserProfileBase):

    class EducationLevel(models.TextChoices):
        BASIC_GENERAL = 'BGE', 'Основное общее образование'
        SECONDARY_GENERAL = 'SGE', 'Среднее общее образование'
        SECONDARY_VOCATIONAL = 'SVE', 'Среднее профессиональное образование'
        HIGHER_BACHELOR = 'HBE', 'Высшее образование (бакалавриат)'
        HIGHER_MASTER = 'HME', 'Высшее образование (магистратура)'
        HIGHER_POSTGRADUATE = 'HPE', 'Высшее образование (аспирантура)'
        __empty__ = 'Выберите Ваш уровень образования:'

    user = models.OneToOneField(
        verbose_name='Пользователь',
        to=User,
        on_delete=models.CASCADE,
        related_name='teacher_profile',
        limit_choices_to={'role': User.Role.TEACHER},
    )
    rates = models.ManyToManyField(
        to=Rate,
        through=TeacherRateAssignment,
        through_fields=('teacher_profile', 'rate'),
        verbose_name='Тарифы',
        blank=True,
        related_name='teacher_rate_profiles',
    )
    education_level = models.CharField(
        verbose_name='Уровень образования',
        max_length=EDUCATION_CODE_LENGTH,
        choices=EducationLevel.choices,
    )

    class Meta(UserProfileBase.Meta):
        db_table = 'teacher_profile'
        verbose_name = 'Профиль преподавателя'
        verbose_name_plural = 'Профили преподавателей'
        indexes = [
            models.Index(
                fields=['telegram_username'],
                name='telegram_username_idx',
            ),
        ]

    def __str__(self):
        return f'Профиль преподавателя {self.user.get_first_last_name()}'


class StudentProfile(UserProfileBase):

    user = models.OneToOneField(
        verbose_name='Пользователь',
        to=User,
        on_delete=models.CASCADE,
        related_name='student_profile',
        limit_choices_to={'role': User.Role.STUDENT},
    )
    rates = models.ManyToManyField(
        to=Rate,
        through=StudentRateAssignment,
        through_fields=('student_profile', 'rate'),
        verbose_name='Тарифы',
        blank=True,
        related_name='student_rate_profiles',
    )

    class Meta(UserProfileBase.Meta):
        db_table = 'student_profile'
        verbose_name = 'Профиль студента'
        verbose_name_plural = 'Профили студентов'
        indexes = [
            models.Index(
                fields=['telegram_username'],
                name='telegram_username_index',
            ),
        ]

    def __str__(self):
        return f'Профиль студента {self.user.get_first_last_name()}'

goodluck_english_school/src/english_school/users/models.py
from django.urls import reverse
from django.utils import timezone
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.conf import settings
from users.validators import phone_validator

from core.constants import (
    USER_ERROR_MESSAGES,
    MEDIUM_FIELD_LENGTH,
    BIG_FIELD_LENGTH,
    MAX_PHONE_LENGTH,
    PRIMARY_KEY_CODE_LENGHT,
)
from core.validators import starts_with_uppercase


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, username,
                     first_name, last_name, password, **extra_fields):
        """
        Create and save a user with the given username, email,
        full_name, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        if not username:
            raise ValueError('The given username must be set')
        if not first_name:
            raise ValueError('The given first name must be set')
        if not last_name:
            raise ValueError('The given last name must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(
            email=email,
            username=username,
            first_name=first_name,
            last_name=last_name,
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, first_name,
                    last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(
            email, username, first_name, last_name, password, **extra_fields,
        )

    def create_superuser(self, email, username, first_name,
                         last_name, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(
            email, username, first_name, last_name, password, **extra_fields,
        )


class StudentManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=User.Role.STUDENT)


class TeacherManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=User.Role.TEACHER)


class User(AbstractBaseUser, PermissionsMixin):

    class Role(models.TextChoices):
        STUDENT = 'student', 'Студент'
        TEACHER = 'teacher', 'Преподаватель'
        __empty__ = 'Выберите Вашу роль:'

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        verbose_name='Логин',
        max_length=MEDIUM_FIELD_LENGTH,
        unique=True,
        help_text=(
            'Обязательное поле. Не более 100 символов. '
            'Можно использовать алфавит латиницы, цифры и символы @/./+/-/'
        ),
        validators=[username_validator],
        error_messages={
            'unique': USER_ERROR_MESSAGES['USERNAME_UNIQUE_ERROR'],
        },
    )
    password = models.CharField(
        verbose_name='Пароль',
        max_length=BIG_FIELD_LENGTH,
    )
    email = models.EmailField(
        verbose_name='Email',
        unique=True,
        error_messages={
            'unique': USER_ERROR_MESSAGES.get('EMAIL_UNIQUE_ERROR'),
        },
    )
    phone_number = models.CharField(
        verbose_name='Номер телефона',
        max_length=MAX_PHONE_LENGTH,
        unique=True,
        blank=True,
        null=True,
        validators=[phone_validator],
        error_messages={
            'unique': (USER_ERROR_MESSAGES.get('PHONE_UNIQUE_ERROR')),
        },
        help_text="В формате +7XXXXXXXXXX или 8XXXXXXXXXX",
    )
    last_login_ip = models.GenericIPAddressField(
        verbose_name='IP-адрес клиента',
        protocol='ipv4',
        blank=True,
        null=True,
        help_text='Последний IP-адрес входа в систему',
    )
    last_login = models.DateTimeField(
        verbose_name='Последний вход',
        blank=True,
        null=True,
        help_text='Дата и время последнего входа.',
    )
    role = models.SlugField(
        verbose_name='Роль',
        max_length=PRIMARY_KEY_CODE_LENGHT,
        choices=Role.choices,
        db_index=True,
        help_text='Роль пользователя в системе.',
    )
    first_name = models.CharField(
        verbose_name='Имя',
        max_length=MEDIUM_FIELD_LENGTH,
        validators=[starts_with_uppercase],
    )
    last_name = models.CharField(
        verbose_name='Фамилия',
        max_length=BIG_FIELD_LENGTH,
        null=True,
        blank=True,
        validators=[starts_with_uppercase],
    )
    patronymic = models.CharField(
        verbose_name='Отчество',
        max_length=MEDIUM_FIELD_LENGTH,
        null=True,
        blank=True,
        help_text='При наличии',
        validators=[starts_with_uppercase],
    )
    is_staff = models.BooleanField(
        verbose_name='Статус персонала',
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name='Активен',
        default=True,
    )
    is_news_sub = models.BooleanField(
        verbose_name='Подписка на рассылку',
        default=False,
        help_text=('Указывает, получает ли пользователь '
                   'новостную рассылку на электронную почту.'),
    )
    date_joined = models.DateTimeField(
        verbose_name='Регистрация',
        default=timezone.now,
        help_text='Дата и время регистрации.',
    )

    objects = UserManager()
    students = StudentManager()
    teachers = TeacherManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ['-date_joined']
        indexes = [
            models.Index(
                fields=['-date_joined', 'last_login'],
                name='activity_idx',
                ),
        ]

    def __str__(self):
        return f'{self.first_name} [{self.username}] {self.last_name}'

    def set_deleted_value(self):
        return f'[DELETED] {self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse(
            'profiles:profile_detail',
            kwargs={'username': self.username},
        )

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        return f'{self.first_name} {self.patronymic}'

    def get_first_last_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_short_name(self):
        return self.first_name

    def email_user(
        self,
        subject,
        message,
        from_email=settings.DEFAULT_FROM_EMAIL,
        **kwargs,
    ):
        send_mail(subject, message, from_email, [self.email], **kwargs)

goodluck_english_school/src/english_school/profiles/forms.py
from django import forms
from django.forms import widgets

from .models import TeacherProfile, StudentProfile


class ProfileEditFormMixin(forms.ModelForm):

    class Meta:
        widgets = {
            'birthday_date': widgets.SelectDateWidget(years=range(1900, 2008)),
        }


class TeacherProfileEditForm(ProfileEditFormMixin):

    class Meta(ProfileEditFormMixin.Meta):
        model = TeacherProfile
        fields = (
            'bio',
            'education_level',
            'gender_code',
            'birthday_date',
            'image',
            'telegram_username',
        )


class StudentProfileEditForm(ProfileEditFormMixin):

    class Meta(ProfileEditFormMixin.Meta):
        model = StudentProfile
        fields = (
            'bio',
            'gender_code',
            'birthday_date',
            'image',
            'telegram_username',
        )

goodluck_english_school/src/english_school/templates/profiles/profile.html
{% extends "base.html" %}
{% load custom_tags %}
{% load static %}

{% block title %}
  Профиль пользователя {{ data.user.get_first_last_name }}
{% endblock title %}

{% block content %}
{% if request.user != data.user %}
  <style>
    .card-link {
      display: none;
    }
    .history-lesson {
      display: none;
    }
  </style>
{% endif %}
<div class="container">
  <div class="row gy-4">
      <div class="col-lg-6">
        <div class="card card-profile rounded-4 shadow-sm">
          <div class="card-body d-flex">
            <div class="mb-0 pb-0">
              {% include 'includes/profiles/photo_image.html' with size_code="big" obj=data.profile %}
            </div>
            <div class="ms-3 d-flex flex-column justify-content-between w-100">
              <div>
                <h3 class="card-title mb-0">{{ data.user.first_name }} {{ data.user.last_name }}</h5>
                <p class="card-text text-role">{{data.user.get_role_display}}</p>
              </div>
              {% if data.user.role == "teacher" %}
                <p class="card-text text-edu-level mt-auto mb-0">{{data.profile.get_education_level_display}}</p>
              {% endif %}
              <p class="card-text text-age mt-auto">{{ data.user_age }} {{ data.user_age|custom_pluralize:"год,года,лет" }}</p>
              <a class="card-link btn btn-primary mb-0 mt-auto py-0 text" href="{% url 'profiles:user_edit' data.user.username %}">Редактировать пользователя</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="card card-profile card-profile-rate rounded-4 shadow-sm"
        style="background-image: url('{% if data.profile.rates.last %}{{ data.profile.rates.last.theme_image.url }}{% else %}{% static '' %}{% endif %}');">
        <div class="card-body d-flex flex-column justify-content-between align-items-center h-100">
          <h5 class="card-title mb-0">Тариф</h5>
          <p class="text-rate mb-auto mt-auto">{% if data.profile.rates.all %}{{ data.profile.rates.last.title|truncatechars:15 }}{% else %}Отсутствует{% endif %}</p>
          {% if data.user.role != "teacher" %}
            <a class="card-link btn btn-secondary mb-0 py-0 text w-100 text bg-secondary" href="{% url 'services:services_list' %}">{% if data.profile.rates.all %}Сменить{% else %}Установить{% endif %}</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="row my-4">
    <div class="col">
      <div class="card card-profile card-profile-main rounded-4 shadow-sm">
        <h5 class="card-header text text-center fw-bold">Основная информация</h5>
        <div class="card-body d-flex flex-column">
          {% if data.profile.bio %}
            <div class="card-article-bio d-flex flex-column rounded-3 bg-warning bg-opacity-25 px-2 py-1 mb-3">
              <p class="article-title">О себе:</p>
              <p class="article-text" id="bio">{{ data.profile.bio|linebreaksbr }}</p>
            </div>
          {% endif %}
          <div class="card-article-main d-flex flex-column align-items-center rounded-3 bg-info bg-opacity-50 px-2 py-1 mb-3">
            <p class="article-title">Логин:</p>
            <p class="article-text" id="username">{{ data.user.username }}</p>
          </div>
          <div class="card-article d-flex flex-column flex-lg-row justify-content-between">
            {% include "includes/profiles/profile_data_line.html" with title="Адрес электронной почты:" data=data.user.email %}
            {% include "includes/profiles/profile_data_line.html" with title="Номер телефона:" data=data.user.phone_number %}
          </div>
          <div class="card-article d-flex flex-column flex-lg-row mt-2">
            {% with data.profile.gender_code as gender_code %}
              {% if gender_code %}
                {% include "includes/profiles/profile_data_line.html" with title="Пол:" data=data.profile.get_gender_code_display %}
              {% else %}
                {% include "includes/profiles/profile_data_line.html" with title="Пол:" data=data.profile.gender_code %}
              {% endif %}
            {% endwith %}
            {% include "includes/profiles/profile_data_line.html" with title="Дата рождения:" data=data.profile.birthday_date %}
          </div>
          <div class="card-article d-flex flex-column justify-content-between flex-lg-row mt-2">
            {% include "includes/profiles/profile_data_line.html" with title="Telegram:" data=data.profile.telegram_username %}
            {% include "includes/profiles/profile_data_line.html" with title="Подписка на рассылку:" data=data.user.is_news_sub is_have_parameter="true" %}
          </div>
          <a class="card-link btn btn-primary mt-3 text w-100 py-2" id="card-profile-main-button" href="{% url 'profiles:profile_edit' data.user.username %}">Редактировать данные профиля</a>
        </div>
      </div>
    </div>
  </div>
  {% include 'includes/lessons/lessons_history.html' with card_title="История завершенных занятий" %}
</div>
{% endblock content %}

goodluck_english_school/src/english_school/templates/profiles/profile_update.html
{% extends "base.html" %}
{% load django_bootstrap5 %}


{% block title %}Редактирование {% if is_edit_user %}пользователя{% else %}профиля{% endif %}{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="card">
        <div class="card-header text-center fw-medium">
          Изменение данных {% if is_edit_user %}пользователя{% else %}профиля{% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button content="Сменить пароль" button_type="link" href="/auth/password_change/" button_class="btn-primary mb-3"%}
            {% bootstrap_button button_type="submit" content="Сохранить изменения" %}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}